version: '3'

services:

  # Code
  arc:
    ports: [ "3333:3333" ]
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - WEBHOOK_URL
      - SIGNING_SECRET
    command: arc sandbox
    volumes:
      - ".:/app:cached"
    tty: true
    stdin_open: true
